# permissions for end users to edit sparkjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sparkjob-editor-role
rules:
- apiGroups:
  - spark.my.domain
  resources:
  - sparkjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spark.my.domain
  resources:
  - sparkjobs/status
  verbs:
  - get
