# permissions for end users to view sparkjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sparkjob-viewer-role
rules:
- apiGroups:
  - spark.my.domain
  resources:
  - sparkjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spark.my.domain
  resources:
  - sparkjobs/status
  verbs:
  - get
